name: npm - manage dist tag
run-name: npm - manage dist tag: ${{ github.event.inputs.tagAction}} ${{ github.event.inputs.tagName}} (on ${{ github.event.inputs.targetVersion}})

on:
  workflow_dispatch:
    inputs:
      tagAction:
        description: 'What action do you want to do with the tag?'
        type: choice
        options:
          - 'add'
          - 'rm'
        required: true
      tagName:
        description: 'What is the name of the dist tag to be managed (created/updated or deleted)?'
        type: string
        required: true
      targetVersion:
        description: 'Version to act on (Only needed with `add` in format of semver version, otherwise `---`).'
        type: string
        required: false

jobs:
  manage_tag:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        env:
          THE_INPUT: '${{ toJson(github.event.inputs) }}'
        run: |
          echo "$THE_INPUT"

      - name: Input 2
        run: |
          echo "${{ env.VERSION }}"
        env:
          # Secrets
          # Note: must use personal access token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Used by the script
          VERSION: ${{ github.event.inputs.targetVersion && format('@{0}', github.event.inputs.targetVersion) || '' }}
